import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    welcome: "Welcome to VisionAI",
    subtitle: "AI-powered eye health screening for everyone",
    startTest: "Start Eye Test",
    refractiveTest: "Vision Acuity Test",
    colorBlindTest: "Color Vision Test",
    education: "Eye Health Education",
    testDescription: "Check your vision clarity with our AI-powered test",
    colorDescription: "Detect color vision deficiencies and get tips for daily adaptation.",
    educationDescription: "Learn about eye health and prevention",
    instructions: "Instructions",
    begin: "Begin Test",
    next: "Next",
    submit: "Submit",
    results: "Results",
    normal: "Normal Vision",
    visitDoctor: "Please visit an eye doctor for further examination",
    readLetter: "What letter do you see?",
    selectNumber: "What number do you see?",
    cantSee: "I can't see clearly",
    eyeHealthTitle: "Eye Health Education",
    aboutRefractive: "About Refractive Errors",
    aboutColor: "About Color Blindness",
    preventionTips: "Prevention Tips",
    leftEye: "Left Eye",
    rightEye: "Right Eye",
    dontKnow: "I don't know",
    leftEyeInstruction: "Please cover your right eye and click Start to begin the test for your left eye.",
    rightEyeInstruction: "Please cover your left eye and click Start to begin the test for your right eye.",
    lettersGetSmaller: "You'll see letters that get smaller as you progress",
    clickOrDontKnow: "Click the letter you see clearly, or 'I don't know' if unsure",
    back: "Back",
    start: "Start",
    correct: "Correct",
    returnToTests: "Return to Tests",
    refractive1: "Refractive errors occur when your eye doesn't bend light correctly, causing blurred vision.",
    refractive2: "Common types include myopia (nearsightedness), hyperopia (farsightedness), and astigmatism.",
    refractive3: "These conditions affect millions of people in India and can often be corrected with glasses or contact lenses.",
    refractive4: "Early detection is important for maintaining good vision and preventing eye strain.",
    color1: "Color blindness affects the ability to distinguish between certain colors, most commonly red and green.",
    color2: "It's usually inherited and affects about 8% of men and 0.5% of women globally.",
    color3: "While there's no cure, people with color vision deficiency can live normal lives with some adaptations.",
    color4: "Special glasses and apps can help distinguish colors in daily activities.",
    prevention1: "Protect your eyes from UV rays by wearing sunglasses outdoors.",
    prevention2: "Take regular breaks from screens using the 20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.",
    prevention3: "Maintain a healthy diet rich in vitamins A, C, and E, and omega-3 fatty acids.",
    prevention4: "Get regular eye examinations, especially if you have a family history of eye problems.",
    prevention5: "Avoid rubbing your eyes and maintain good hygiene to prevent infections.",
    educationSubtitle: "Learn about eye health and how to protect your vision",
    importantNoteTitle: "Important Note",
    importantNote1: "These tests are screening tools and cannot replace professional medical examination.",
    importantNote2: "If you have concerns about your vision, please consult with a qualified eye care professional.",
    eyesHealthy: "Your eyes are perfectly fine. No need to visit a doctor.",
    colorBlindInstructions1: "Look at each colored dot pattern carefully",
    colorBlindInstructions2: "Enter the number you see within the pattern",
    colorBlindInstructions3: "If you can't see any number, enter '0'",
    colorBlindInstructions4: "Take your time with each plate",
    colorBlindPlateProgress: "Plate {current} of {total}",
    colorBlindPlaceholder: "Enter number",
    colorBlindNormal: "Normal color vision detected",
    colorBlindMild: "Mild color vision deficiency detected",
    colorBlindSignificant: "Significant color vision deficiency detected. Please consult an eye specialist.",
    colorBlindTypeNormal: "Normal",
    colorBlindTypeMild: "Mild Deficiency",
    colorBlindTypeSignificant: "Color Vision Deficiency",
    colorBlindSummary: "Test Summary:",
    colorBlindCorrect: "Correct responses: {correct} out of {total}",
    back: "Back",
    returnToTests: "Return to Tests",
    heroBadge: "No login required • 100% private • Instant results",
    chooseTest: "Choose Your Eye Test",
    chooseTestDesc: "Select from our AI-powered screening tests designed for accuracy and accessibility",
    learnMore: "Learn More",
    feature1Title: "AI-Powered Accuracy",
    feature1Desc: "Advanced algorithms provide reliable screening results",
    feature2Title: "Multilingual Support",
    feature2Desc: "Available in English, Hindi, and Tamil",
    feature3Title: "Developed by Abhimanyu Chaudhary",
    feature3Desc: "Designed and built with care for everyone.",
    ctaTitle: "Early Detection, Better Vision",
    ctaDesc: "Join thousands who have already screened their vision with VisionAI",
    ctaStart: "Start Vision Test",
    ctaLearn: "Learn More",
    notFoundOops: "Oops! Page not found",
    notFoundReturnHome: "Return to Home",
    close: "Close",
    languageSelectTitle: "Select your language",
    languageSelectDesc: "Please choose your preferred language to continue.",
    languageEnglish: "English",
    languageHindi: "Hindi",
    languageTamil: "Tamil",
    medicationReminder: "Medication Reminder",
    medicationTime: "Time for Dose",
    medicationFrequency: "Frequency",
    medicationDose: "Dose (optional)",
    medicationSet: "Set Reminder",
    medicationDaily: "Daily",
    medicationEvery12h: "Every 12 hours",
    medicationEvery8h: "Every 8 hours",
    medicationNextDose: "Next dose: {time}",
    medicationPermission: "Allow notifications to get reminders!",
    medicationPermissionDenied: "Notifications are blocked. Please enable them in your browser settings.",
    medicationReminderMsg: "Time for your eye drop dose!",
    medicationVoiceGuide: "This section helps you set reminders for your eye medication."
  },
  hi: {
    welcome: "VisionAI में आपका स्वागत है",
    subtitle: "सभी के लिए AI-संचालित नेत्र स्वास्थ्य जांच",
    startTest: "आंख की जांच शुरू करें",
    refractiveTest: "दृष्टि तीक्ष्णता परीक्षण",
    colorBlindTest: "रंग दृष्टि परीक्षण",
    education: "नेत्र स्वास्थ्य शिक्षा",
    testDescription: "हमारे AI-संचालित परीक्षण से अपनी दृष्टि की स्पष्टता जांचें",
    colorDescription: "रंग दृष्टि दोष का पता लगाएं और दैनिक जीवन के लिए सुझाव पाएं।",
    educationDescription: "नेत्र स्वास्थ्य और रोकथाम के बारे में जानें",
    instructions: "निर्देश",
    begin: "परीक्षण शुरू करें",
    next: "अगला",
    submit: "जमा करें",
    results: "परिणाम",
    normal: "सामान्य दृष्टि",
    visitDoctor: "कृपया आगे की जांच के लिए नेत्र चिकित्सक से मिलें",
    readLetter: "आप कौन सा अक्षर देख रहे हैं?",
    selectNumber: "आप कौन सी संख्या देख रहे हैं?",
    cantSee: "मैं स्पष्ट रूप से नहीं देख सकता",
    eyeHealthTitle: "नेत्र स्वास्थ्य शिक्षा",
    aboutRefractive: "अपवर्तक त्रुटियों के बारे में",
    aboutColor: "रंग अंधता के बारे में",
    preventionTips: "रोकथाम की युक्तियां",
    leftEye: "बायां आंख",
    rightEye: "दायां आंख",
    dontKnow: "मुझे नहीं पता",
    leftEyeInstruction: "कृपया अपनी दाहिनी आंख को ढकें और अपने बाएं आंख के लिए परीक्षण शुरू करने के लिए 'शुरू करें' पर क्लिक करें।",
    rightEyeInstruction: "कृपया अपनी बाईं आंख को ढकें और अपने दाहिने आंख के लिए परीक्षण शुरू करने के लिए 'शुरू करें' पर क्लिक करें।",
    lettersGetSmaller: "जैसे-जैसे आप आगे बढ़ेंगे, अक्षर छोटे होते जाएंगे",
    clickOrDontKnow: "जो अक्षर स्पष्ट दिखे उसे क्लिक करें, या यदि स्पष्ट नहीं है तो 'मुझे नहीं पता' चुनें",
    back: "वापस",
    start: "शुरू करें",
    correct: "सही",
    returnToTests: "परीक्षणों पर लौटें",
    refractive1: "अपवर्तक त्रुटियाँ तब होती हैं जब आपकी आंख प्रकाश को सही ढंग से नहीं मोड़ती, जिससे धुंधली दृष्टि होती है।",
    refractive2: "आम प्रकारों में मायोपिया (निकट दृष्टि दोष), हाइपरोपिया (दूर दृष्टि दोष), और एस्टिग्मैटिज्म शामिल हैं।",
    refractive3: "ये स्थितियाँ भारत में लाखों लोगों को प्रभावित करती हैं और अक्सर चश्मा या कॉन्टैक्ट लेंस से सुधारी जा सकती हैं।",
    refractive4: "जल्दी पहचान अच्छी दृष्टि बनाए रखने और आंखों के तनाव को रोकने के लिए महत्वपूर्ण है।",
    color1: "रंग अंधता कुछ रंगों के बीच अंतर करने की क्षमता को प्रभावित करती है, सबसे आम रूप से लाल और हरा।",
    color2: "यह आमतौर पर आनुवंशिक होती है और लगभग 8% पुरुषों और 0.5% महिलाओं को प्रभावित करती है।",
    color3: "हालांकि इसका कोई इलाज नहीं है, रंग दृष्टि दोष वाले लोग कुछ अनुकूलनों के साथ सामान्य जीवन जी सकते हैं।",
    color4: "विशेष चश्मा और ऐप्स दैनिक गतिविधियों में रंगों को पहचानने में मदद कर सकते हैं।",
    prevention1: "बाहर धूप में चश्मा पहनकर अपनी आंखों को UV किरणों से बचाएं।",
    prevention2: "20-20-20 नियम का पालन करते हुए स्क्रीन से नियमित ब्रेक लें: हर 20 मिनट में, 20 फीट दूर किसी चीज को 20 सेकंड तक देखें।",
    prevention3: "विटामिन A, C, और E, और ओमेगा-3 फैटी एसिड से भरपूर स्वस्थ आहार लें।",
    prevention4: "नियमित रूप से आंखों की जांच कराएं, खासकर यदि आपके परिवार में आंखों की समस्याओं का इतिहास है।",
    prevention5: "अपनी आंखों को रगड़ने से बचें और संक्रमण से बचाव के लिए अच्छी स्वच्छता बनाए रखें।",
    educationSubtitle: "नेत्र स्वास्थ्य और अपनी दृष्टि की सुरक्षा के बारे में जानें",
    importantNoteTitle: "महत्वपूर्ण नोट",
    importantNote1: "ये परीक्षण केवल स्क्रीनिंग टूल हैं और पेशेवर चिकित्सा जांच का विकल्प नहीं हो सकते।",
    importantNote2: "यदि आपको अपनी दृष्टि के बारे में कोई चिंता है, तो कृपया योग्य नेत्र देखभाल विशेषज्ञ से परामर्श करें।",
    eyesHealthy: "आपकी आंखें पूरी तरह से स्वस्थ हैं। डॉक्टर से मिलने की आवश्यकता नहीं है।",
    colorBlindInstructions1: "प्रत्येक रंगीन डॉट पैटर्न को ध्यान से देखें",
    colorBlindInstructions2: "पैटर्न में जो संख्या दिखे, उसे दर्ज करें",
    colorBlindInstructions3: "अगर कोई संख्या नहीं दिखती है, तो '0' दर्ज करें",
    colorBlindInstructions4: "हर प्लेट के साथ अपना समय लें",
    colorBlindPlateProgress: "प्लेट {current} में से {total}",
    colorBlindPlaceholder: "संख्या दर्ज करें",
    colorBlindNormal: "सामान्य रंग दृष्टि पाई गई",
    colorBlindMild: "हल्की रंग दृष्टि दोष पाई गई",
    colorBlindSignificant: "महत्वपूर्ण रंग दृष्टि दोष पाई गई। कृपया नेत्र विशेषज्ञ से परामर्श करें।",
    colorBlindTypeNormal: "सामान्य",
    colorBlindTypeMild: "हल्का दोष",
    colorBlindTypeSignificant: "रंग दृष्टि दोष",
    colorBlindSummary: "परीक्षण सारांश:",
    colorBlindCorrect: "सही उत्तर: {correct} में से {total}",
    back: "वापस",
    returnToTests: "परीक्षणों पर लौटें",
    heroBadge: "कोई लॉगिन आवश्यक नहीं • 100% निजी • त्वरित परिणाम",
    chooseTest: "अपना नेत्र परीक्षण चुनें",
    chooseTestDesc: "हमारे AI-संचालित स्क्रीनिंग परीक्षणों में से चुनें, जो सटीकता और पहुंच के लिए डिज़ाइन किए गए हैं",
    learnMore: "और जानें",
    feature1Title: "AI-संचालित सटीकता",
    feature1Desc: "उन्नत एल्गोरिदम विश्वसनीय स्क्रीनिंग परिणाम प्रदान करते हैं",
    feature2Title: "बहुभाषी समर्थन",
    feature2Desc: "अंग्रेज़ी, हिंदी और तमिल में उपलब्ध",
    feature3Title: "अभिमन्यु चौधरी द्वारा विकसित",
    feature3Desc: "हर किसी के लिए देखभाल के साथ डिज़ाइन और निर्मित।",
    ctaTitle: "जल्दी पहचान, बेहतर दृष्टि",
    ctaDesc: "हजारों लोग पहले ही VisionAI के साथ अपनी दृष्टि की जांच कर चुके हैं",
    ctaStart: "दृष्टि परीक्षण शुरू करें",
    ctaLearn: "और जानें",
    notFoundOops: "अरे! पृष्ठ नहीं मिला",
    notFoundReturnHome: "मुख्य पृष्ठ पर लौटें",
    close: "बंद करें",
    languageSelectTitle: "अपनी भाषा चुनें",
    languageSelectDesc: "कृपया जारी रखने के लिए अपनी पसंदीदा भाषा चुनें।",
    languageEnglish: "अंग्रेज़ी",
    languageHindi: "हिंदी",
    languageTamil: "तमिल",
    medicationReminder: "दवा अनुस्मारक",
    medicationTime: "खुराक का समय",
    medicationFrequency: "आवृत्ति",
    medicationDose: "खुराक (वैकल्पिक)",
    medicationSet: "अनुस्मारक सेट करें",
    medicationDaily: "रोज़ाना",
    medicationEvery12h: "हर 12 घंटे में",
    medicationEvery8h: "हर 8 घंटे में",
    medicationNextDose: "अगली खुराक: {time}",
    medicationPermission: "अनुस्मारक प्राप्त करने के लिए सूचनाओं की अनुमति दें!",
    medicationPermissionDenied: "सूचनाएं अवरुद्ध हैं। कृपया अपने ब्राउज़र सेटिंग्स में उन्हें सक्षम करें।",
    medicationReminderMsg: "अपनी आंखों की दवा लेने का समय हो गया है!",
    medicationVoiceGuide: "यह अनुभाग आपकी दवा के लिए अनुस्मारक सेट करने में मदद करता है."
  },
  ta: {
    welcome: "VisionAI க்கு வரவேற்கிறோம்",
    subtitle: "அனைவருக்கும் AI-இயங்கும் கண் ஆரோக்கிய பரிசோதனை",
    startTest: "கண் பரிசோதனையைத் தொடங்கவும்",
    refractiveTest: "பார்வைக் கூர்மை பரிசோதனை",
    colorBlindTest: "வண்ண பார்வை பரிசோதனை",
    education: "கண் ஆரோக்கிய கல்வி",
    testDescription: "எங்கள் AI-இயங்கும் பரிசோதனையுடன் உங்கள் பார்வைத் தெளிவைச் சரிபார்க்கவும்",
    colorDescription: "வண்ண பார்வைக் குறைபாடுகளைக் கண்டறிந்து, தினசரி வாழ்வுக்கான உதவிகளைப் பெறுங்கள்.",
    educationDescription: "கண் ஆரோக்கியம் மற்றும் தடுப்பு பற்றி அறியவும்",
    instructions: "வழிமுறைகள்",
    begin: "பரிசோதனையைத் தொடங்கவும்",
    next: "அடுத்து",
    submit: "சமர்ப்பிக்கவும்",
    results: "முடிவுகள்",
    normal: "சாதாரண பார்வை",
    visitDoctor: "மேலும் பரிசோதனைக்கு கண் மருத்துவரைப் பார்க்கவும்",
    readLetter: "நீங்கள் எந்த எழுத்தைப் பார்க்கிறீர்கள்?",
    selectNumber: "நீங்கள் எந்த எண்ணைப் பார்க்கிறீர்கள்?",
    cantSee: "எனக்கு தெளிவாகப் பார்க்க முடியவில்லை",
    eyeHealthTitle: "கண் ஆரோக்கிய கல்வி",
    aboutRefractive: "ஒளிவிலகல் பிழைகள் பற்றி",
    aboutColor: "வண்ண குருட்டுத்தன்மை பற்றி",
    preventionTips: "தடுப்பு குறிப்புகள்",
    leftEye: "இடது கண்",
    rightEye: "வலது கண்",
    dontKnow: "எனக்கு தெரியவில்லை",
    leftEyeInstruction: "தயவுசெய்து உங்கள் வலது கண் மூடிக் கொண்டு இடது கண் பரிசோதனைக்கு 'தொடங்கு' என்பதை அழுத்தவும்.",
    rightEyeInstruction: "தயவுசெய்து உங்கள் இடது கண் மூடிக் கொண்டு வலது கண் பரிசோதனைக்கு 'தொடங்கு' என்பதை அழுத்தவும்.",
    lettersGetSmaller: "நீங்கள் முன்னேறும்போது எழுத்துக்கள் சிறிதாகும்",
    clickOrDontKnow: "நீங்கள் தெளிவாகப் பார்க்கும் எழுத்தை கிளிக் செய்யவும், அல்லது தெரியவில்லை என்றால் 'எனக்கு தெரியவில்லை' என்பதை தேர்வு செய்யவும்",
    back: "பின்னுக்கு",
    start: "தொடங்கு",
    correct: "சரி",
    returnToTests: "பரிசோதனைகளுக்கு திரும்பவும்",
    refractive1: "ஒளிவிலகல் பிழைகள் உங்கள் கண் ஒளியை சரியாக வளைத்துவிடாதபோது ஏற்படுகிறது, இது மங்கலான பார்வையை ஏற்படுத்துகிறது.",
    refractive2: "பொதுவான வகைகளில் மயோபியா (நெருக்கமான பார்வை), ஹைபரோபியா (தூர பார்வை), மற்றும் அஸ்டிக்மாட்டிசம் அடங்கும்.",
    refractive3: "இந்த நிலைகள் இந்தியாவில் மில்லியன் கணக்கான மக்களை பாதிக்கின்றன மற்றும் பெரும்பாலும் கண்ணாடி அல்லது தொடர்பு லென்ஸ்கள் மூலம் சரி செய்யப்படலாம்.",
    refractive4: "ஆரம்பத்தில் கண்டறிதல் நல்ல பார்வையை பராமரிக்கவும் கண் சோர்வைத் தடுக்கும் வகையிலும் முக்கியமானது.",
    color1: "வண்ணக் குருட்டுத்தன்மை சில வண்ணங்களை வேறுபடுத்தும் திறனை பாதிக்கிறது, பொதுவாக சிவப்பு மற்றும் பச்சை.",
    color2: "இது பெரும்பாலும் மரபணு சார்ந்தது மற்றும் உலகளவில் சுமார் 8% ஆண்கள் மற்றும் 0.5% பெண்களை பாதிக்கிறது.",
    color3: "இதற்கு சிகிச்சை இல்லை என்றாலும், வண்ணக் குறைபாடு உள்ளவர்கள் சில மாற்றங்களுடன் சாதாரண வாழ்க்கை வாழலாம்.",
    color4: "சிறப்பு கண்ணாடிகள் மற்றும் செயலிகள் தினசரி செயல்பாடுகளில் வண்ணங்களை வேறுபடுத்த உதவும்.",
    prevention1: "வெளியில் சூரியக்கதிர்களில் சன்னல் அணிந்து உங்கள் கண்களை பாதுகாக்கவும்.",
    prevention2: "20-20-20 விதியைப் பின்பற்றி திரைகளிலிருந்து வழக்கமான இடைவெளிகளை எடுக்கவும்: ஒவ்வொரு 20 நிமிடத்திற்கும், 20 அடி தூரத்தில் உள்ள ஒன்றைப் பார்க்கவும் 20 விநாடிகள்.",
    prevention3: "விட்டமின் A, C, மற்றும் E மற்றும் ஓமேகா-3 கொழுப்பு அமிலங்கள் நிறைந்த ஆரோக்கியமான உணவை உட்கொள்ளவும்.",
    prevention4: "உங்கள் குடும்பத்தில் கண் பிரச்சனைகளுக்கான வரலாறு இருந்தால் கூட, கண்களை வழக்கமாக பரிசோதிக்கவும்.",
    prevention5: "உங்கள் கண்களை உரசுவதைத் தவிர்க்கவும் மற்றும் தொற்றுகளைத் தடுக்கும் வகையில் நல்ல சுகாதாரத்தை பராமரிக்கவும்.",
    educationSubtitle: "கண் ஆரோக்கியம் மற்றும் உங்கள் பார்வையை எப்படி பாதுகாப்பது என்பதை அறிக",
    importantNoteTitle: "முக்கிய குறிப்பு",
    importantNote1: "இந்த பரிசோதனைகள் திரைமுக கருவிகள் மட்டுமே, மருத்துவ பரிசோதனையை மாற்ற முடியாது.",
    importantNote2: "உங்கள் பார்வை குறித்து கவலை இருந்தால், தகுதியான கண் பராமரிப்பு நிபுணரை அணுகவும்.",
    eyesHealthy: "உங்கள் கண்கள் முழுமையாக நலமாக உள்ளன. கண் மருத்துவரை பார்க்க தேவையில்லை.",
    colorBlindInstructions1: "ஒவ்வொரு வண்ண புள்ளி வடிவத்தையும் கவனமாகப் பாருங்கள்",
    colorBlindInstructions2: "வடிவத்தில் நீங்கள் பார்க்கும் எண்ணை உள்ளிடவும்",
    colorBlindInstructions3: "எந்த எண்ணும் தெரியவில்லை என்றால் '0' என்பதை உள்ளிடவும்",
    colorBlindInstructions4: "ஒவ்வொரு தட்டுக்கும் உங்கள் நேரத்தை எடுத்துக்கொள்ளுங்கள்",
    colorBlindPlateProgress: "தட்டு {current} / {total}",
    colorBlindPlaceholder: "எண்ணை உள்ளிடவும்",
    colorBlindNormal: "சாதாரண வண்ண பார்வை கண்டறியப்பட்டது",
    colorBlindMild: "லேசான வண்ண பார்வை குறைபாடு கண்டறியப்பட்டது",
    colorBlindSignificant: "முக்கியமான வண்ண பார்வை குறைபாடு கண்டறியப்பட்டது. தயவுசெய்து கண் நிபுணரை அணுகவும்.",
    colorBlindTypeNormal: "சாதாரணம்",
    colorBlindTypeMild: "லேசான குறைபாடு",
    colorBlindTypeSignificant: "வண்ண பார்வை குறைபாடு",
    colorBlindSummary: "பரிசோதனை சுருக்கம்:",
    colorBlindCorrect: "சரியான பதில்கள்: {correct} / {total}",
    back: "பின்னுக்கு",
    returnToTests: "பரிசோதனைகளுக்கு திரும்பவும்",
    heroBadge: "உள்நுழைவு தேவையில்லை • 100% தனிப்பட்டது • உடனடி முடிவுகள்",
    chooseTest: "உங்கள் கண் பரிசோதனையைத் தேர்ந்தெடுக்கவும்",
    chooseTestDesc: "நம்பகமான முடிவுகளுக்காக எங்கள் AI இயக்கும் பரிசோதனைகளைத் தேர்ந்தெடுக்கவும்",
    learnMore: "மேலும் அறிக",
    feature1Title: "AI இயக்கும் துல்லியம்",
    feature1Desc: "மேம்பட்ட வழிமுறைகள் நம்பகமான முடிவுகளை வழங்குகின்றன",
    feature2Title: "பலமொழி ஆதரவு",
    feature2Desc: "ஆங்கிலம், ஹிந்தி மற்றும் தமிழ் மொழிகளில் கிடைக்கிறது",
    feature3Title: "அபிமன்யு சௌத்ரி உருவாக்கியது",
    feature3Desc: "அனைவருக்கும் அக்கறையுடன் வடிவமைக்கப்பட்டது மற்றும் உருவாக்கப்பட்டது.",
    ctaTitle: "ஆரம்ப கண்டறிதல், சிறந்த பார்வை",
    ctaDesc: "ஆயிரக்கணக்கானோர் ஏற்கனவே VisionAI மூலம் தங்கள் பார்வையை பரிசோதித்துள்ளனர்",
    ctaStart: "பார்வை பரிசோதனையைத் தொடங்கவும்",
    ctaLearn: "மேலும் அறிக",
    notFoundOops: "அய்யோ! பக்கம் கிடைக்கவில்லை",
    notFoundReturnHome: "முகப்புக்கு திரும்பவும்",
    close: "மூடு",
    languageSelectTitle: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    languageSelectDesc: "தொடர உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
    languageEnglish: "ஆங்கிலம்",
    languageHindi: "ஹிந்தி",
    languageTamil: "தமிழ்",
    medicationReminder: "மருந்து நினைவூட்டல்",
    medicationTime: "மருந்து நேரம்",
    medicationFrequency: "அடிக்கடி",
    medicationDose: "மருந்து அளவு (விரும்பினால்)",
    medicationSet: "நினைவூட்டலை அமைக்கவும்",
    medicationDaily: "தினமும்",
    medicationEvery12h: "ஒவ்வொரு 12 மணி நேரத்திற்கும்",
    medicationEvery8h: "ஒவ்வொரு 8 மணி நேரத்திற்கும்",
    medicationNextDose: "அடுத்த மருந்து: {time}",
    medicationPermission: "நினைவூட்டல்களுக்கு அறிவிப்புகளை அனுமதிக்கவும்!",
    medicationPermissionDenied: "அறிவிப்புகள் தடுக்கப்பட்டுள்ளன. உங்கள் உலாவி அமைப்புகளில் அவற்றை இயக்கவும்.",
    medicationReminderMsg: "உங்கள் கண் மருந்து நேரம்!",
    medicationVoiceGuide: "இந்த பகுதி உங்கள் கண் மருந்துக்கான நினைவூட்டலை அமைக்க உதவுகிறது."
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<string>(() => {
    if (typeof window !== 'undefined') {
      return localStorage.getItem('visionai-language') || 'en';
    }
    return 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('visionai-language', language);
    }
  }, [language]);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
